# application: flaskapp
# version: 1
# runtime: python27
# api_version: 1
# threadsafe: true

# handlers:
# - url: /.*
#   script: app.app
# - url: /_ah/queue/deferred
#   script: app.deferred_application
#   login: admin
# # - url: /_ah/queue/deferred
# #   script: google.appengine.ext.deferred.deferred.application
# #   login: admin

# builtins:
# - deferred: off

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app
- url: /_ah/queue/deferred.*
  script: app.deferred_application
  login: admin

builtins:
- deferred: off